# Generated by Django 5.2.1 on 2025-05-16 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('user_message', models.TextField()),
                ('bot_message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='userprofile.UserProfile'
                )),
            ],
        ),
    ]
