# Generated by Django 5.2.1 on 2025-05-16 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openaichat', '0001_initial'),
        ('userprofile', '0002_alter_userprofile_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.userprofile'),
        ),
    ]
