# Generated by Django 5.2.1 on 2025-05-17 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_alter_userprofile_family'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={'verbose_name_plural': 'families'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('facilitator', 'Facilitator'), ('family_member', 'Family Member')], default='family_member', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userprofile.family'),
        ),
    ]
