# Generated by Django 5.2.1 on 2025-05-17 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_alter_family_options_userprofile_user_type_and_more'),   # noqa
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='userprofile.family'),  # noqa
        ),
    ]
